package cn.lgw.learn.mapper;

import cn.lgw.learn.domain.TestDO;
import cn.lgw.learn.domain.condition.TestCondition;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int countByExample(TestCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int deleteByExample(TestCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int insert(TestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int insertSelective(TestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    List<TestDO> selectByExample(TestCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    TestDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestDO record, @Param("example") TestCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int updateByExample(@Param("record") TestDO record, @Param("example") TestCondition example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int updateByPrimaryKeySelective(TestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbggenerated Thu Jan 24 10:15:51 CST 2019
     */
    int updateByPrimaryKey(TestDO record);
}